# Autogenerated wrapper script for qpOASES_mumps_jll for armv7l-linux-gnueabihf-cxx11
export libqpOASES, libqpOASES_MUMPS

using MUMPS_seq_jll
using OpenBLAS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("qpOASES_mumps")
JLLWrappers.@declare_library_product(libqpOASES, "libqpOASES.so.3.2")
JLLWrappers.@declare_library_product(libqpOASES_MUMPS, "libqpOASES_MUMPS.so.3.2")
function __init__()
    JLLWrappers.@generate_init_header(MUMPS_seq_jll, OpenBLAS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libqpOASES,
        "lib/libqpOASES.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqpOASES_MUMPS,
        "lib/libqpOASES_MUMPS.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
